### ISSUE TITLE
Research converting report generator into Rails-based micro-service on EC2 instance

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#70]
MSC2 is deployed on a custom EC2 instance, which doesn't currently have all the tooling Heroku does. It's deployed on custom infrastructure only because of the report generator feature, which has numerous dependencies. We should consider wrapping this feature in a Rails app, with some basic authentication and have it work as an external service so that it is a separate the main app.

**Comment by mzagaja** [comment]
While I know you prefer putting things on Heroku I just want to warn you there is a lot of potential pain and pitfalls to be found on this path. The reason is that we are running into the limitations of Heroku as a host with this and some of our other apps. The big issue ends up being performance (round trips between the two servers greatly increase the amount of time to get anything done) but also it creates two new places where things can go wrong. I think the least painful path, in the long run, is to view it as MySchoolCommute2 has graduated from Heroku to EC2. While putting these apps on the vanilla Linux servers comes with challenges, splitting the app will not give us the luxury of averting them. We're now signing ourselves up for figuring out both problems with the EC2 microservice and the Heroku app.

**Comment by allthesignals** [comment]
Matt Z: Simple apps can easily live in the world of Heroku. Once we get into apps that are a little more complex, we run into limitations of Heroku. The process _fighting_ with Heroku's buildpack design is more costly than just standing up a complicated app.

**Comment by allthesignals** [comment]
Matt Z: The overhead cost of maintaining a separate micro-service (2 apps) is more expensive than maintaining 1 app on custom infrastructure.

**Comment by allthesignals** [comment]
MZ: Microservices make sense when 2 or more other apps depending on that microservice, which then makes sense.
